### ISSUE TITLE
Can't get Koch to install nim under Windows

### ISSUE THREAD

**Issue by bncastle** [Araq/Nim#2061]
Hello,

I am able to build the bootstrap Nim compiler and successfully get it to bootstrap and build Nim itself. Where I run into trouble is when I try to install it.

*koch install c:\compiler\nim\bin*

it fails when it tries to do sh ./install.sh which is of course a Unix command.  I poked around a bit to see if there was a corresponding install.bat but could not find one. It appears there is no support for using Koch to install Nim under Windows. Is this true? Is Windows support planned for this?
Thanks.

**Comment by kirbyfan64** [comment]
Koch can generate an NSIS installer script, so you could try that:

```
C:\some_dir> koch nsis
```

**Comment by Varriount** [comment]
I don't quite see *why* you need to use the install command - what would it do? . It's available for *nix systems because they have a particular convention for the location of various resources (executables, library files, etc). Windows has no such convention, as program files are traditionally installed in the "Program Files" directory, or for development tools that will be modifying their own source,  the root drive directory.
