### ISSUE TITLE
[PROPOSAL] Have getEnv() throw an error instead of returning "" in case the variable doesn't exist

### ISSUE THREAD

**Issue by axbender** [Araq/Nim#2120]
Currently I find it quite tedious to check the existance/setting of environment variables. Please consider the following snippets:

```
let yygnu = getEnv("YYGNU").string
if len(yygnu) == 0: quit("%YYGNU% is not defined!")
let cp = yygnu & r"\cp.exe"

let yybin = getEnv("YYBIN").string
if len(yybin) == 0: quit("%YYBIN% is not defined!")
let osinfo = yybin & r"\osinfo.exe"
```

This could be written more easily (and clearly) as

```
try:
   let yygnu = getEnv("YYGNU").string
   let yybin = getEnv("YYBIN").string
except:
   echo "The required variable %", ..., "% is not defined"

let
   cp     = yygnu & r"\cp.exe"
   osinfo = yybin & r"\osinfo.exe"
```

**Comment by def-** [comment]
On the one hand the terminal doesn't handle unset variables as an error either, so `echo $YYGNU` just prints an empty string.

On the other hand the current behaviour makes it easier to create bugs like this in Nim: https://github.com/ValveSoftware/steam-for-linux/issues/3671

**Comment by Araq** [comment]
No.

**Comment by Varriount** [comment]
@axbender As an explanation, modifying getEnv to throw an exception would cause backwards compatibility issues, as well as needless performance problems (throwing exceptions usually incurs overhead).

Since your chief concern seems to be code duplication, is there any reason why you can't use a procedure like the one below? It would almost certainly be inlined, or you could make it a template.

```nimrod
proc getEnvEx(s: string): string =  
  result = getEnv(s)
  if result.len == 0:
    e: ValueError
    e.msg = "Environment variable '" + s + "' doesn't exist."
    raise e
```

**Comment by dom96** [comment]
@Varriount I don't think that code will work. You need to use ``newException(ValueError, "...")``.
