### ISSUE TITLE
Hard to describe compiler bug with generics/cast/proc

### ISSUE THREAD

**Issue by oderwat** [Araq/Nim#2176]
Sorry for the title but I can't imagine a better one.

While playing with some code to create another variant of a toTable from zip'ed arrays I ran into this:

```nimrod
import tables, sequtils
 
let keys = @['a','b','c']
let values = @[1, 2, 3]

proc asKeyVal[T](x: T): auto = cast[seq[tuple[key: char, val: int]]](x)

echo toTable zip(keys, values).asKeyVal

proc toTable[A, B](pairs: openArray[tuple[a: A, b: B]]): Table[A, B] =
  toTable(pairs.asKeyVal)

echo toTable zip(keys, values)
```
with the following (strange!) output:
```
{a: 1, b: 2, c: 3}
{b: 2, c: 3, 
```
What happens there?

**Comment by Araq** [comment]
The problem is with this:
```nim

proc toTable[A, B](pairs: openArray[tuple[a: A, b: B]]): Table[A, B] =
  toTable(pairs.asKeyVal)
```

Here your cast in 'asKeyVal' is invalid, as you *cast* an openArray to a seq which is invalid and thanks to 'cast' the compiler shuts up and doesn't tell you. That 'echo' doesn't report the resulting binary zero surely doesn't help to detect the bug, but that's another bug which is hard to fix (thanks to multi-threading and portability we cannot do much better than generating 'printf("%s", "abc")' for 'echo "abc"')

**Comment by oderwat** [comment]
But why is it working in one case but not in the other? Also related https://github.com/Araq/Nim/issues/2126 which is the origin of that cast - which I did not even thought about - that is from a Rosetta Code example (made by @def-).

**Comment by oderwat** [comment]
OPS... Sorry:
