### ISSUE TITLE
asm code in templates fail

### ISSUE THREAD

**Issue by Araq** [Araq/Nim#2362]
```nim

template x1(name: string) =
  var hi, lo: uint32
  asm """
    rdtsc
    :"=a"(`lo`), "=d"(`hi`)
  """
  var cycles = int64(lo) or (int64(hi) shl 32)
  
  echo name, " cycles=", cycles

when isMainModule:
  x1("ok")
```

**Comment by Araq** [comment]
This is a feature in the compiler ("top level assembler statements") and even if I change the behaviour this code cannot possibly work: hi and lo are gensym'ed variables and as such cannot be captured in an asm statement easily for technical reasons but even if that would work, 'hi' and 'lo' are declared as global variables in the C code and so the assembler might not be able to deal with this. You have to use a proc here.

**Comment by winksaville** [comment]
Hmmm,

The following code works fine:

template x1(name: string, v: uint32) =
    var hi, lo: uint32

    hi = 0
    lo = v

    #asm """
    #  rdtsc
    #  :"=a"(`lo`), "=d"(`hi`)
    #"""
    var cycles = int64(lo) or (int64(hi) shl 32)

    echo name, " cycles=", cycles

when isMainModule:
    x1("ok1", 1)


Looking at nimcache/test_asm.c I see the variables hi, lo and cycles are globals:

NU32 hi_88205;
NU32 lo_88207;
NI64 cycles_88209;

And the template code is in test_asmInit:

NIM_EXTERNC N_NOINLINE(void, test_asmInit)(void) {
	NimStringDesc* LOC1;
	hi_88205 = ((NU32) 0);
	lo_88207 = ((NU32) 1);
	cycles_88209 = (NI64)(((NI64) (lo_88207)) | (NI64)((NU64)(((NI64) (hi_88205))) << (NU64)(IL64(32))));
	LOC1 = 0;
	LOC1 = nimInt64ToStr(cycles_88209);
	printf("%s%s%s\012", (((NimStringDesc*) &TMP5))->data, (((NimStringDesc*) &TMP6))->data, (LOC1)->data);
}

So it seems you're treating asm as "gensym" variables rather than statements, as in the failing case the "asm" code is global not in test_asmInit where I would have expected it.

I can simulate what I expect by invoking the x1 template inside of a proc and uncomment the "asm" statement:

template x1(name: string, v: uint32) =
    var hi, lo: uint32

    hi = 0
    lo = v

    asm """
      rdtsc
      :"=a"(`lo`), "=d"(`hi`)
    """
    var cycles = int64(lo) or (int64(hi) shl 32)

    echo name, " cycles=", cycles

when isMainModule:
    proc myproc() =
      x1("ok1", 1)

    myproc()

Now the generated myproc looks exactly as I'd expect:

N_NIMCALL(void, myproc_88204)(void) {
	NU32 hi_88207;
	NU32 lo_88209;
	NI64 cycles_88211;
	NimStringDesc* LOC1;
	hi_88207 = 0;
	lo_88209 = 0;
	hi_88207 = ((NU32) 0);
	lo_88209 = ((NU32) 1);
	asm("      rdtsc\n"
      :"=a"(lo), "=d"(hi)
);
	cycles_88211 = (NI64)(((NI64) (lo_88209)) | (NI64)((NU64)(((NI64) (hi_88207))) << (NU64)(IL64(32))));
	LOC1 = 0;
	LOC1 = nimInt64ToStr(cycles_88211);
	printf("%s%s%s\012", (((NimStringDesc*) &TMP5))->data, (((NimStringDesc*) &TMP6))->data, (LOC1)->data);
}

The hi, lo and cycles are local gensym'd variables in myproc and it would have compiled if nim compiler had processed the hi, lo backticked variables in the output section of the asm statement and converted them to the gensym'd local variable names.

So from my perspective I see two "bugs". First asm's in globally invoked templates should be treated as statements and generated in the test_asmInit code. The other is that backticked variables in asm statements should not be literal but mapped to the gensym'd variable.

Of course, I could be totally mixed up. Side note: thanks for creating nim, its been fun learning it!
