### ISSUE TITLE
Implicit conversion from `int` to `float`

### ISSUE THREAD

**Issue by alendit** [Araq/Nim#2661]
Hi,

I've found a strange behaviour with implicit `int` conversion in proc parameters:

```
from math import pow

var a, b = 1

echo(pow(a+b, 2))  # Error: type mismatch: got (int, int literal(2))

echo(pow(2, 2)) # works fine

echo(pow(float(a+b), 2))  # works fine, too
```

Intuitively, I would expect statements 1 and 2 both to either fail or succeed.

**Comment by def-** [comment]
That looks totally fine to me. By writing `var a = 1` you make `a` an int. If you don't want that, use `const` instead of `var`.

**Comment by alendit** [comment]
@def- I am surprised that `int literal` is converted to float implicitly, but `int` isn't. If it's by design than you can close the issue.

**Comment by bluenote10** [comment]
@alendit: I guess the reasoning behind this is that `int literal` can be converted statically at compile time, whereas an `int` in general has to be converted at runtime. If you define `const a = 1; const b = 1` you get the same behavior as an `int literal` because the compiler again can convert at compile time.

**Comment by alendit** [comment]
@bluenote10 It makes sense. I'll close this one, then.
