### ISSUE TITLE
Undocumented template

### ISSUE THREAD

**Issue by apense** [Araq/Nim#2886]
In the systems module, the template `-|` is undocumented. I would do it, and I will if you want, but I can't figure out the use. I'm guessing it has something to do with indexing. In case anyone reading this is interested, here's some example code:

```nim
var s = -2 -| @[1, 2, 3, 4, 5, 6] # gives 4, which is the length of the sequence + (-2)
var t = 19 -| @[1,2,3] # gives 19, since it's >= 0
```

EDIT: I should mention that I mean it's undocumented in the code. Other templates, while documented in the code, don't have their documentation show up on the website. That might be an issue in itself.
EDIT 2: I can't search for `-|` on Github because of search limitations, which is why I can't figure out the use.

**Comment by kirbyfan64** [comment]
Source code is in [`system.nim`, line 2862](https://github.com/Araq/Nim/blob/devel/lib/system.nim#L2862):

```nim
template `-|`*(b, s: expr): expr =
  (if b >= 0: b else: s.len + b)
```

I think it's for calculating negative slices (or was??...because now we have the `^x` syntax). For instance:

```nim
var seq = @[1, 2, 3, 4, 5, 6]
seq[-2 -| seq] # same as seq[^2]
seq[3 -| seq] # same as seq[3]
```

A quick grep shows absolutely *no* usage in the standard library. It is used once in the compiler sources: [`compiler/ast.nim`, lines 952-953](https://github.com/Araq/Nim/blob/devel/compiler/ast.nim#L952). I believe the first use can be replaced by just `n[i]`; not sure about the second.

**Comment by apense** [comment]
Should it be deprecated, then? It's an odd convenience function to have.

**Comment by dom96** [comment]
It was made public by @zah in 2012 in this commit: https://github.com/Araq/Nim/commit/770d4a997eab25a04cdfd83b325491a2e63bea08

Maybe he can tell us what this was for.

**Comment by Araq** [comment]
Just more the template to where the compiler uses it and remove it from system please.

**Comment by apense** [comment]
Seems to only show up in ast.nim. I'll make a PR for it. Let me know if somebody finds it elsewhere.
